spring:
  application:
    name: GestionDesSons

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://dpg-d6th3b24d50c73capvbg-a/batiss_music_db}
    username: ${DATABASE_USERNAME:batiss_music_db_user}
    password: ${DATABASE_PASSWORD:6CrKaLB4Q0n959jXPosYoMGKc4BggdFA}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  # Désactiver Spring Security temporairement
  security:
    user:
      name: admin
      password: admin

server:
  port: ${PORT:8080}

app:
  secret-key: hghhjisadewderet56546546456454
  expiration-time: 86400000
  wave-url: https://pay.wave.com/m/M_sn_BR5I1NOjNKcr/c/sn/?amount=2000

google:
  drive:
    file-id: 1zO6CExYz6WkPtc-hoRRHX_XIELD3VEqT  # ← mets l'ID réel ici

cors:
  allowed-origins: "http://localhost:5500,http://127.0.0.1:5500"  # ← plus précis que "*"